# Generated by Django 4.1.2 on 2022-10-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('police_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('police_name_english', models.CharField(max_length=200)),
                ('police_name_bangla', models.CharField(max_length=200)),
                ('police_rank', models.CharField(choices=[('IGP', 'আইজিপি'), ('EIG', 'অতিঃ আইজি'), ('DIG', 'ডিআইজি'), ('EDIG', 'অতিঃ ডিআইজি'), ('SP', 'এসপি'), ('ESP', 'অতিঃ এসপি'), ('SSP', 'সিনিয়র এসপি'), ('ASP', 'এএসপি'), ('I', 'ইন্সপেক্টর'), ('SI', 'এসআই'), ('ASI', 'এএসআই')], default='I', max_length=4)),
            ],
        ),
    ]
