# Generated by Django 4.1.2 on 2022-10-10 20:26

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('police_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_name_english', models.CharField(max_length=200, verbose_name='Name in English')),
                ('police_name_bangla', models.CharField(max_length=200, verbose_name='Name in Bangla')),
                ('police_rank', models.CharField(choices=[('IGP', 'আইজিপি'), ('Addl. IG', 'অতিঃ আইজি'), ('DIG', 'ডিআইজি'), ('Addl. DIG', 'অতিঃ ডিআইজি'), ('SP', 'এসপি'), ('Addl. SP', 'অতিঃ এসপি'), ('Sr. SP', 'সিনিয়র এসপি'), ('ASP', 'এএসপি'), ('Sr. ASP', 'সিনিয়র এএসপি'), ('I', 'ইন্সপেক্টর'), ('SI', 'এসআই'), ('ASI', 'এএসআই'), ('NA', 'প্রযোজ্য নহে')], default='NA', max_length=10, verbose_name='Rank')),
                ('police_image', models.ImageField(default='logo.jpeg', upload_to=reports.models.user_directory_path, verbose_name='Picture')),
                ('police_dob', models.DateField(default=reports.models.get_default_dob, verbose_name='Date of Birth')),
                ('police_created', models.DateTimeField(auto_now_add=True)),
                ('police_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
