# Generated by Django 4.1.2 on 2022-10-10 21:59

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('police_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='পুলিশর আইডি নং')),
                ('police_name_english', models.CharField(default='', max_length=200, verbose_name='নাম (ইংরেজি)')),
                ('police_name_bangla', models.CharField(default='', max_length=200, verbose_name='নাম (বাংলা)')),
                ('police_merit', models.CharField(default='', max_length=5, verbose_name='PSC Merit List')),
                ('police_present', models.CharField(default='', max_length=200, verbose_name='বর্তমান কর্মস্থল')),
                ('police_past', models.CharField(default='', max_length=2000, verbose_name='পূর্ববর্তী কর্মস্থল সমূহ')),
                ('police_comments', models.CharField(default='', max_length=200, verbose_name='Observation Comment')),
                ('police_mobile', models.CharField(default='', max_length=200, verbose_name='ফোন নম্বর')),
                ('police_edu', models.CharField(default='', max_length=200, verbose_name='শিক্ষাগত যোগ্যতা')),
                ('police_rank', models.CharField(choices=[('IGP', 'আইজিপি'), ('Addl. IG', 'অতিঃ আইজি'), ('DIG', 'ডিআইজি'), ('Addl. DIG', 'অতিঃ ডিআইজি'), ('SP', 'এসপি'), ('Addl. SP', 'অতিঃ এসপি'), ('Sr. SP', 'সিনিয়র এসপি'), ('ASP', 'এএসপি'), ('Sr. ASP', 'সিনিয়র এএসপি'), ('I', 'ইন্সপেক্টর'), ('SI', 'এসআই'), ('ASI', 'এএসআই'), ('NA', 'প্রযোজ্য নহে')], default='NA', max_length=10, verbose_name='বর্তমান পদবী')),
                ('police_joining_rank', models.CharField(choices=[('ASP', 'এএসপি'), ('I', 'ইন্সপেক্টর'), ('SI', 'এসআই'), ('ASI', 'এএসআই')], default='ASP', max_length=10, verbose_name='চাকুরীতে যোগদানের পদ')),
                ('police_present_status', models.CharField(choices=[('On Job', 'চাকুরীরত'), ('Sacked', 'চাকুরীচ্যুত'), ('Retired', 'অবসরপ্রাপ্ত')], default='On Job', max_length=10, verbose_name='বর্তমান অবস্থা')),
                ('police_batch', models.CharField(choices=[('7', '7'), ('8', '8'), ('12', '12'), ('15', '15'), ('17', '17'), ('18', '18'), ('20', '20'), ('21', '21'), ('22', '22'), ('24', '24'), ('25', '25'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36')], default='36', max_length=5, verbose_name='বিসিএস ব্যাচ')),
                ('police_religion', models.CharField(choices=[('Islam', 'ইসলাম'), ('Hindu', 'হিন্দু'), ('Christian', 'খ্রিস্টান'), ('Buddha', 'বৌদ্ধ'), ('Others', 'অন্যান্য')], default='Islam', max_length=10, verbose_name='ধর্ম')),
                ('police_blood_group', models.CharField(choices=[('A+', ''), ('A-', ''), ('B+', ''), ('B-', ''), ('AB+', ''), ('AB-', ''), ('O+', ''), ('O-', '')], default='O+', max_length=10, verbose_name='রক্তের গ্রুপ')),
                ('police_gender', models.CharField(choices=[('Male', ''), ('Female', '')], default='Male', max_length=10, verbose_name='লিঙ্গ')),
                ('police_district', models.CharField(choices=[('কুমিল্লা', 'কুমিল্লা'), ('ফেনী', 'ফেনী'), ('ব্রাহ্মণবাড়িয়া', 'ব্রাহ্মণবাড়িয়া'), ('রাঙ্গামাটি', 'রাঙ্গামাটি'), ('নোয়াখালী', 'নোয়াখালী'), ('চাঁদপুর', 'চাঁদপুর'), ('লক্ষ্মীপুর', 'লক্ষ্মীপুর'), ('চট্টগ্রাম', 'চট্টগ্রাম'), ('কক্সবাজার', 'কক্সবাজার'), ('খাগড়াছড়ি', 'খাগড়াছড়ি'), ('বান্দরবান', 'বান্দরবান'), ('সিরাজগঞ্জ', 'সিরাজগঞ্জ'), ('পাবনা', 'পাবনা'), ('বগুড়া', 'বগুড়া'), ('রাজশাহী', 'রাজশাহী'), ('নাটোর', 'নাটোর'), ('জয়পুরহাট', 'জয়পুরহাট'), ('চাঁপাইনবাবগঞ্জ', 'চাঁপাইনবাবগঞ্জ'), ('নওগাঁ', 'নওগাঁ'), ('যশোর', 'যশোর'), ('সাতক্ষীর', 'সাতক্ষীর'), ('মেহেরপুর', 'মেহেরপুর'), ('নড়াইল', 'নড়াইল'), ('চুয়াডাঙ্গা', 'চুয়াডাঙ্গা'), ('কুষ্টিয়া', 'কুষ্টিয়া'), ('মাগুরা', 'মাগুরা'), ('খুলনা', 'খুলনা'), ('বাগেরহাট', 'বাগেরহাট'), ('ঝিনাইদহ', 'ঝিনাইদহ'), ('ঝালকাঠি', 'ঝালকাঠি'), ('পটুয়াখালী', 'পটুয়াখালী'), ('পিরোজপুর', 'পিরোজপুর'), ('বরিশাল', 'বরিশাল'), ('ভোলা', 'ভোলা'), ('বরগুনা', 'বরগুনা'), ('সিলেট', 'সিলেট'), ('মৌলভীবাজার', 'মৌলভীবাজার'), ('হবিগঞ্জ', 'হবিগঞ্জ'), ('সুনামগঞ্জ', 'সুনামগঞ্জ'), ('নরসিংদী', 'নরসিংদী'), ('গাজীপুর', 'গাজীপুর'), ('শরীয়তপুর', 'শরীয়তপুর'), ('নারায়ণগঞ্জ', 'নারায়ণগঞ্জ'), ('টাঙ্গাইল', 'টাঙ্গাইল'), ('কিশোরগঞ্জ', 'কিশোরগঞ্জ'), ('মানিকগঞ্জ', 'মানিকগঞ্জ'), ('ঢাকা', 'ঢাকা'), ('মুন্সিগঞ্জ', 'মুন্সিগঞ্জ'), ('রাজবাড়ী', 'রাজবাড়ী'), ('মাদারীপুর', 'মাদারীপুর'), ('গোপালগঞ্জ', 'গোপালগঞ্জ'), ('ফরিদপুর', 'ফরিদপুর'), ('পঞ্চগড়', 'পঞ্চগড়'), ('দিনাজপুর', 'দিনাজপুর'), ('লালমনিরহাট', 'লালমনিরহাট'), ('নীলফামারী', 'নীলফামারী'), ('গাইবান্ধ', 'গাইবান্ধ'), ('ঠাকুরগাঁও', 'ঠাকুরগাঁও'), ('রংপুর', 'রংপুর'), ('কুড়িগ্রাম', 'কুড়িগ্রাম'), ('শেরপুর', 'শেরপুর'), ('ময়মনসিংহ', 'ময়মনসিংহ'), ('জামালপুর', 'জামালপুর'), ('নেত্রকোণা', 'নেত্রকোণা')], default='কুমিল্লা', max_length=50, verbose_name='নিজ জেলা')),
                ('police_image', models.ImageField(default='logo.jpeg', upload_to=reports.models.user_directory_path, verbose_name='ছবি')),
                ('police_dob', models.DateField(default=reports.models.get_default_dob, verbose_name='জন্ম তারিখ')),
                ('police_created', models.DateTimeField(auto_now_add=True)),
                ('police_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
