# Generated by Django 4.1.2 on 2022-10-10 07:55

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='police_image',
            field=models.ImageField(default='static/logo.jpeg', upload_to=reports.models.user_directory_path),
        ),
    ]
