# Generated by Django 4.1.2 on 2022-10-10 09:11

from django.db import migrations, models
import django.utils.timezone
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_police_police_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='police_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='police',
            name='police_dob',
            field=models.DateField(default=reports.models.get_default_my_date, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='police',
            name='police_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_image',
            field=models.ImageField(default='logo.jpeg', upload_to=reports.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_name_bangla',
            field=models.CharField(max_length=200, verbose_name='Name in Bangla'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_name_english',
            field=models.CharField(max_length=200, verbose_name='Name in English'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_rank',
            field=models.CharField(choices=[('IGP', 'আইজিপি'), ('EIG', 'অতিঃ আইজি'), ('DIG', 'ডিআইজি'), ('EDIG', 'অতিঃ ডিআইজি'), ('SP', 'এসপি'), ('ESP', 'অতিঃ এসপি'), ('SSP', 'সিনিয়র এসপি'), ('ASP', 'এএসপি'), ('I', 'ইন্সপেক্টর'), ('SI', 'এসআই'), ('ASI', 'এএসআই')], default='I', max_length=4, verbose_name='Rank'),
        ),
    ]
