# Generated by Django 4.1.2 on 2022-10-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_police_police_family_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='police_designation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='কর্মরত পদ'),
        ),
    ]
