# Generated by Django 4.1.2 on 2022-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_police_police_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='police_comments',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
