# Generated by Django 4.1.2 on 2022-10-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_police_police_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='police_address_permanent',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_address_present',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
