# Generated by Django 4.1.2 on 2022-10-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_police_police_address_permanent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='police_image_url',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='ছবি (S3)'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_address_permanent',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='স্থায়ী ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_address_present',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='বর্তমান ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_comments',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='পর্যবেক্ষণ মন্তব্য'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_family_background',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='পারিবারিক ইতিহাস'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_joining_rank',
            field=models.CharField(choices=[('ASP', 'এএসপি'), ('Inspector', 'ইন্সপেক্টর'), ('SI', 'এসআই'), ('ASI', 'এএসআই')], default='ASP', max_length=10, verbose_name='চাকুরীতে যোগদানের পদ'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_past',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='পূর্ববর্তী কর্মস্থল সমূহ'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_political_background',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='রাজনৈতিক ইতিহাস'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_rank',
            field=models.CharField(choices=[('IGP', 'আইজিপি'), ('Addl. IG', 'অতিঃ আইজি'), ('DIG', 'ডিআইজি'), ('Addl. DIG', 'অতিঃ ডিআইজি'), ('SP', 'এসপি'), ('Addl. SP', 'অতিঃ এসপি'), ('Sr. SP', 'সিনিয়র এসপি'), ('ASP', 'এএসপি'), ('Sr. ASP', 'সিনিয়র এএসপি'), ('Inspector', 'ইন্সপেক্টর'), ('SI', 'এসআই'), ('ASI', 'এএসআই'), ('NA', 'প্রযোজ্য নহে')], default='NA', max_length=10, verbose_name='বর্তমান পদবী'),
        ),
    ]
