# Generated by Django 4.1.2 on 2022-10-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_police_police_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='police_image_url',
        ),
    ]
