# Generated by Django 4.1.2 on 2022-10-14 15:55

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_police_police_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='police_image',
            field=models.ImageField(default='logo.png', upload_to=reports.models.user_directory_path, verbose_name='ছবি'),
        ),
    ]
